feat: added k3s_flannel_iface and k3s_node_external_ip options
PyratLabs/ansible-role-k3s pull request #140
Opened 2021-08-16 13:03 UTC by m1m1x

## TITLE

### Summary

This PR add 2 new options in node inventory : 
- k3s_node_external_ip
- k3s_flannel_iface

Those options allow to select on which interface k3s should bind on the cluster nodes. This is especially useful should your cluster nodes have multiple network interfaces. By default, k3s select the first one (except for lo). 

### Issue type

- Documentation
- Feature

### Test instructions

This PR was tested with 3 nodes running Ubuntu 20.04.
Host inventory was defined this way: 
```
[k3s]
192.168.56.220 k3s_control_node=true k3s_flannel_iface=enp0s8 k3s_node_external_ip=192.168.56.220
192.168.56.221
192.168.56.222
```

### Acceptance Criteria

### Additional Information

2021-08-16 19:10 UTC, xanmanning commented
Hi @m1m1x 

This shouldn't be necessary, see:

- [Server (Control Plane) Configuration](https://github.com/PyratLabs/ansible-role-k3s#server-control-plane-configuration)
- [K3s Server Configuration Reference](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/)

In your example, the `host_vars` for `192.168.56.220` should be:

```yaml
---

k3s_control_node: true
k3s_server:
  node-external-ip: 192.168.56.220
  flannel-iface: enp0s8
```

2021-08-16 19:13 UTC, xanmanning requested changes
As mentioned in [my comment](https://github.com/PyratLabs/ansible-role-k3s/pull/140#issuecomment-899752411), these should not be necessary, however I have supplied suggestions for your own project with the tidier Ansible syntax.

2021-08-16 19:13 UTC, xanmanning commented on templates/k3s.service.j2
> +    --node-external-ip {{ hostvars[inventory_hostname].k3s_node_external_ip }}
```suggestion
    --node-external-ip {{ k3s_node_external_ip }}
```

2021-08-16 19:13 UTC, xanmanning commented on templates/k3s.service.j2
> +    {% if 'k3s_node_external_ip' in hostvars[inventory_hostname] %}
```suggestion
    {% if k3s_node_external_ip is defined %}
```

2021-08-16 19:13 UTC, xanmanning commented on templates/k3s.service.j2
> +    {% if 'k3s_flannel_iface' in hostvars[inventory_hostname] %}
```suggestion
    {% if k3s_flannel_iface is defined %}
```

2021-08-16 19:13 UTC, xanmanning commented on templates/k3s.service.j2
> +    --flannel-iface {{ hostvars[inventory_hostname].k3s_flannel_iface }}
```suggestion
    --flannel-iface {{ k3s_flannel_iface }}
```

2021-08-16 20:43 UTC, m1m1x commented
Hi @xanmanning !
Thanks for your feedback, I should have read more carefully the documentation :)
Thanks also for your review, but I won't keep my project.

Quick question : I was about to create another PR to enable support for custom kubelet config file (for instance to increase the maxPods per node value). Did I miss something or should I continue the PR?

2021-08-17 07:13 UTC, xanmanning commented
I don't think k3s supports kubelet config files, rather it does the (now deprecated in kubelet) config flag: 

https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#customized-flags

Example when using this role for worker (agent) nodes:

---

k3s_agent:
  kubelet-arg:
    - "max-pods=200"

2021-08-17 20:55 UTC, m1m1x commented
Thanks again, your solution works smoothly!

By the way, this role is a very nice project of yours and we enjoy to use it.

2021-08-17 20:55 UTC, closed without merging